# Offense count: 2
Metrics/AbcSize:
  Max: 23

# Offense count: 17
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 114

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 19
# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Offense count: 2
Style/ClassVars:
  Exclude:
    - 'lib/wtt/core/paths.rb'

Style/RedundantBegin:
  Exclude:
    - 'lib/wtt/core.rb'

Lint/RescueException:
  Exclude:
    - 'lib/wtt/core.rb'
    - 'lib/wtt/core/tracer.rb'